language: go
os: linux

go:
  - 1.14.x

git:
  depth: false

services:
  - docker

env:
  global:
    - STRUCTOR_VERSION=v1.10.0
    - STRUCTOR_LATEST_TAG=$TRAVIS_TAG
    - GO111MODULE=on

install:
  - sudo -E apt-get -yq update
  - >
    sudo -E apt-get -yq --no-install-suggests --no-install-recommends install \
      build-essential \
      autoconf \
      libtool \
      bison \
      flex \
      make \
      libmagic-dev \
      libssl-dev \
      libpcap-dev \
      g++-multilib \
      docker-ce=${DOCKER_VERSION}*
  - sudo -E ./script/travis_setup.sh
  - sudo -E ./script/install_yara.sh

before_script:
  - go mod download

script:
  - make test

before_deploy:
  - sudo -E ./script/build.sh

deploy:
  - provider: releases
    api_key: ${GITHUB_TOKEN}
    file: build/mole*
    file_glob: true
    skip_cleanup: true
    on:
      repo: mole-ids/mole
      tags: true

  - provider: pages
    edge: false
    github_token: ${GITHUB_TOKEN}
    local_dir: site
    skip_cleanup: true
    on:
      repo: mole-ids/mole
      all_branches: true
